Choi-94/WearTheWeather

src/main/java/com/example/weartheweather/dto/AdminBoardDTO.java

관리자게시글dto추가

---

src/main/java/com/example/weartheweather/entity/AdminBoardEntity.java
src/main/java/com/example/weartheweather/entity/AdminBoardFileEntity.java
src/main/java/com/example/weartheweather/entity/AdminBoardLikesEntity.java
src/main/java/com/example/weartheweather/entity/AlarmEntity.java
src/main/java/com/example/weartheweather/entity/CommentEntity.java
src/main/java/com/example/weartheweather/entity/MemberBoardEntity.java
src/main/java/com/example/weartheweather/entity/MemberBoardFileEntity.java
src/main/java/com/example/weartheweather/entity/MemberBoardLikesEntity.java
src/main/java/com/example/weartheweather/entity/PopularKeywordsEntity.java
src/main/java/com/example/weartheweather/entity/RecentKeywordsEntity.java

하영Entity추가

---

src/main/java/com/example/weartheweather/entity/MarketChatEntity.java
src/main/java/com/example/weartheweather/entity/MarketPaymentEntity.java
src/main/java/com/example/weartheweather/entity/MarketProductEntity.java
src/main/java/com/example/weartheweather/entity/MarketProductFileEntity.java
src/main/java/com/example/weartheweather/entity/MarketReportEntity.java

Yh market save 230626

---

src/main/java/com/example/weartheweather/entity/AlarmEntity.java

하영Entity수정

---

build.gradle
src/main/java/com/example/weartheweather/config/MailConfig.java
src/main/java/com/example/weartheweather/controller/MemberController.java
src/main/resources/application.yml
src/main/resources/templates/component/footer.html
src/main/resources/templates/component/nav.html
src/main/resources/templates/memberPages/memberLogin.html
src/main/resources/templates/memberPages/memberSave.html

0627 회원 SAVE중 (이메일 인증번호 작업중)

---

src/main/java/com/example/weartheweather/controller/MarketController.java
src/main/java/com/example/weartheweather/entity/MarketPaymentEntity.java
src/main/java/com/example/weartheweather/entity/MarketProductEntity.java
src/main/java/com/example/weartheweather/entity/MarketReportEntity.java
src/main/resources/templates/marketPages/marketList.html
src/main/resources/templates/marketPages/marketSave.html

MarketSave

---

src/main/java/com/example/weartheweather/controller/MailServiceRestController.java
src/main/java/com/example/weartheweather/entity/MemberEntity.java
src/main/java/com/example/weartheweather/entity/MemberTradeEntity.java
src/main/java/com/example/weartheweather/service/MailServiceInter.java
src/main/java/com/example/weartheweather/service/RegisterMail.java
src/main/resources/templates/memberPages/memberSave.html

0627 회원 SAVE중 (이메일 인증번호 작업 완료)

0627 회원 SAVE중 (이메일 인증번호 작업 완료)

---

src/main/java/com/example/weartheweather/controller/MemberController.java
src/main/java/com/example/weartheweather/dto/MemberDTO.java
src/main/java/com/example/weartheweather/entity/MemberEntity.java
src/main/java/com/example/weartheweather/repository/MemberRepository.java
src/main/java/com/example/weartheweather/service/MemberService.java
src/main/resources/templates/memberPages/memberSave.html

0628 회원 SAVE완료 (인증메일 틀릴시 focus만 적용시켜야함)

0628 회원 SAVE완료

---

src/main/java/com/example/weartheweather/controller/AdminBoardController.java
src/main/java/com/example/weartheweather/dto/AdminBoardDTO.java
src/main/java/com/example/weartheweather/dto/CommentDTO.java
src/main/java/com/example/weartheweather/entity/AdminBoardEntity.java
src/main/java/com/example/weartheweather/entity/AdminBoardFileEntity.java
src/main/java/com/example/weartheweather/entity/AlarmEntity.java
src/main/java/com/example/weartheweather/entity/BaseEntity.java
src/main/java/com/example/weartheweather/entity/CommentEntity.java
src/main/java/com/example/weartheweather/entity/MemberBoardEntity.java
src/main/java/com/example/weartheweather/entity/RecentKeywordsEntity.java
src/main/java/com/example/weartheweather/repository/AdminBoardFileRepository.java
src/main/java/com/example/weartheweather/service/AdminBoardService.java
src/main/resources/templates/weatherCodiPages/boardList.html

관리자게시글 리스트까지 했습니다. 이미지가 안 뜨는데 그 부분은 수정하겠습니다

Hy admin board list 230627

---

src/main/java/com/example/weartheweather/controller/MarketController.java
src/main/java/com/example/weartheweather/dto/MarketDTO.java
src/main/java/com/example/weartheweather/dto/MarketProductDTO.java
src/main/resources/templates/marketPages/marketSave.html
src/main/resources/templates/marketPages/test.html

open weather api 적용 
현재 위치 기준으로 날씨와 기상상태를 받아옴 
// 아이콘 적용 진행중

weather_api_적용중

---

src/main/java/com/example/weartheweather/entity/MemberEntity.java

0628 MemberEntity에서 mappedBy 댓글Entity와의 참조 관계 실수

0628 MemberEntity에서 mappedBy 댓글Entity와의 참조 관계 실수

---

src/main/java/com/example/weartheweather/controller/MemberController.java
src/main/resources/templates/memberPages/memberAnotherSave.html

0628 네이버와 카카오 로그인시 Save처리중

---

src/main/java/com/example/weartheweather/controller/AdminBoardController.java
src/main/java/com/example/weartheweather/service/AdminBoardService.java
src/main/resources/static/css/boardList.css
src/main/resources/templates/weatherCodiPages/boardDetail.html
src/main/resources/templates/weatherCodiPages/boardList.html

Hy admin board detail 230628

---

src/main/java/com/example/weartheweather/controller/AdminBoardController.java
src/main/resources/templates/adminPages/boardSave.html
src/main/resources/templates/weatherCodiPages/boardDetail.html
src/main/resources/templates/weatherCodiPages/boardList.html
src/main/resources/templates/weatherCodiPages/boardUpdate.html

하영_수정페이지 작성완료

---

src/main/java/com/example/weartheweather/controller/AdminBoardController.java
src/main/java/com/example/weartheweather/dto/AdminBoardLikesDTO.java
src/main/java/com/example/weartheweather/entity/AdminBoardEntity.java
src/main/java/com/example/weartheweather/entity/AdminBoardLikesEntity.java
src/main/java/com/example/weartheweather/repository/AdminBoardLikesRepository.java
src/main/java/com/example/weartheweather/repository/AdminBoardRepository.java
src/main/java/com/example/weartheweather/service/AdminBoardService.java
src/main/resources/templates/weatherCodiPages/boardDetail.html
src/main/resources/templates/weatherCodiPages/boardUpdate.html

버튼생성완료. 좋아요 누를 시 count 올라가는지 확인해야됌

Hy board update 0630

---

src/main/java/com/example/weartheweather/config/LoginCheckInterceptor.java
src/main/java/com/example/weartheweather/controller/KakaoController.java
src/main/java/com/example/weartheweather/controller/MemberController.java
src/main/java/com/example/weartheweather/dto/MemberDTO.java
src/main/java/com/example/weartheweather/model/KakaoProfile.java
src/main/java/com/example/weartheweather/repository/MemberRepository.java
src/main/java/com/example/weartheweather/service/MemberService.java
src/main/resources/templates/memberPages/KakaoSave.html
src/main/resources/templates/memberPages/memberLogin.html

[0630 (로그인o , 로그인인터셉터x) , 세션값 닉네임 추가, 카카오로그인(ing, 정보를 불러오는 것까지 가능 --> 
DB에 저장시켜야함)

Dy member save 0630

---

src/main/java/com/example/weartheweather/controller/AdminBoardController.java
src/main/java/com/example/weartheweather/dto/AdminBoardLikesDTO.java
src/main/java/com/example/weartheweather/repository/AdminBoardLikesRepository.java
src/main/java/com/example/weartheweather/service/AdminBoardService.java
src/main/resources/templates/weatherCodiPages/boardDetail.html

하영_좋아요 버튼 임시저장

---

src/main/java/com/example/weartheweather/controller/KakaoController.java
src/main/java/com/example/weartheweather/controller/MemberController.java
src/main/java/com/example/weartheweather/dto/MemberDTO.java
src/main/java/com/example/weartheweather/repository/MemberRepository.java
src/main/java/com/example/weartheweather/service/MemberService.java
src/main/resources/static/css/main.css
src/main/resources/templates/component/header.html
src/main/resources/templates/memberPages/memberLogin.html

0703 회원로그인 에러 잡고 로그아웃 완료, header 수정

0703 회원로그인 에러 잡고 로그아웃 완료, header 수정

---

src/main/java/com/example/weartheweather/controller/AdminBoardController.java
src/main/java/com/example/weartheweather/dto/AdminBoardLikesDTO.java
src/main/java/com/example/weartheweather/repository/AdminBoardLikesRepository.java
src/main/java/com/example/weartheweather/service/AdminBoardService.java
src/main/resources/templates/weatherCodiPages/boardDetail.html

좋아요 기능 수정했고 likesCount 기능만 추가하면 됩니다

하영_좋아요 버튼 기능 수정

---

src/main/java/com/example/weartheweather/dto/MarketProductDTO.java
src/main/resources/templates/component/navMarket.html
src/main/resources/templates/marketPages/marketDetail.html
src/main/resources/templates/marketPages/marketList.html
src/main/resources/templates/marketPages/marketSave.html

+detail layout 수정
+price data 를 포맷팅 추가

+marketDetail 수정중

---

src/main/java/com/example/weartheweather/controller/KakaoController.java
src/main/java/com/example/weartheweather/controller/MemberController.java
src/main/java/com/example/weartheweather/entity/MemberEntity.java
src/main/java/com/example/weartheweather/model/KakaoProfile.java
src/main/resources/templates/component/mypage.html
src/main/resources/templates/myInfoPages/myInfoUpdate.html

0703 카카오 닉네임 따와서 세션값 저장

---

src/main/java/com/example/weartheweather/controller/AdminBoardController.java
src/main/java/com/example/weartheweather/repository/AdminBoardLikesRepository.java
src/main/java/com/example/weartheweather/service/AdminBoardService.java
src/main/resources/templates/weatherCodiPages/boardDetail.html

하영_좋아요 버튼 기능 수정2

---

src/main/java/com/example/weartheweather/controller/KakaoController.java
src/main/java/com/example/weartheweather/controller/MemberController.java
src/main/java/com/example/weartheweather/dto/MemberDTO.java
src/main/java/com/example/weartheweather/entity/MemberEntity.java
src/main/java/com/example/weartheweather/service/MemberService.java
src/main/resources/templates/myInfoPages/myInfoUpdate.html

0703 로그인,저장 로그아웃 완료// 마이페이지에서 수정처리중

0703 로그인,저장 로그아웃 완료// 마이페이지에서 수정처리중

---

src/main/java/com/example/weartheweather/controller/AdminBoardController.java
src/main/java/com/example/weartheweather/dto/AdminBoardLikesDTO.java
src/main/java/com/example/weartheweather/repository/AdminBoardLikesRepository.java
src/main/java/com/example/weartheweather/service/AdminBoardService.java
src/main/resources/templates/weatherCodiPages/boardDetail.html

좋아요 기능 완료했습니다
--추가로 작업해야할 것--
1. 좋아요를 누르면 알림기능
2. 좋아요count axios로 적용
3. 좋아요 받은 작성자는 포인트 +10

하영_좋아요 기능 완료

---

src/main/java/com/example/weartheweather/controller/MarketController.java
src/main/java/com/example/weartheweather/dto/MarketProductDTO.java
src/main/java/com/example/weartheweather/repository/MarketProductRepository.java
src/main/java/com/example/weartheweather/service/MarketProductService.java
src/main/resources/static/css/main.css
src/main/resources/templates/marketPages/marketDetail.html
src/main/resources/templates/marketPages/marketSave.html

+ marketList 끝
+ marketDetail ( 좋아요 -> 구매하기 -> 채팅 ) 순서기능진행
+ marketreport porm 작성

+ marketSave 끝

---

src/main/resources/static/css/main.css
src/main/resources/templates/component/footer.html
src/main/resources/templates/component/header.html
src/main/resources/templates/component/nav.html
src/main/resources/templates/component/navMarket.html
src/main/resources/templates/index.html
src/main/resources/templates/marketPages/marketDetail.html
src/main/resources/templates/marketPages/marketList.html
src/main/resources/templates/marketPages/marketSave.html

+ css 완료
+ 모든활동 비로그인 시 제한
+ 연관상품 (날씨기준) △ 다중이미지파일 <-> 슬라이드
△ marketSave Session 연동
△ 좋아요, 조회수, 타임( ? 일전 )
△ 신고하기
△ 구매하기
△ 채팅하기

marketDetail

---

src/main/java/com/example/weartheweather/controller/AdminBoardController.java
src/main/java/com/example/weartheweather/controller/MemberBoardController.java
src/main/java/com/example/weartheweather/dto/AdminBoardLikesDTO.java
src/main/java/com/example/weartheweather/dto/AlarmDTO.java
src/main/java/com/example/weartheweather/dto/MemberBoardDTO.java
src/main/java/com/example/weartheweather/dto/MemberBoardLikesDTO.java
src/main/java/com/example/weartheweather/entity/AdminBoardLikesEntity.java
src/main/java/com/example/weartheweather/entity/AlarmEntity.java
src/main/java/com/example/weartheweather/entity/MemberBoardEntity.java
src/main/java/com/example/weartheweather/entity/MemberBoardFileEntity.java
src/main/java/com/example/weartheweather/entity/MemberBoardLikesEntity.java
src/main/java/com/example/weartheweather/repository/MemberBoardFileRepository.java
src/main/java/com/example/weartheweather/repository/MemberBoardLikesRepository.java
src/main/java/com/example/weartheweather/repository/MemberBoardRepository.java
src/main/java/com/example/weartheweather/service/MemberBoardService.java
src/main/resources/templates/adminPages/boardSave.html
src/main/resources/templates/codiContestPages/boardDetail.html
src/main/resources/templates/codiContestPages/boardList.html
src/main/resources/templates/codiContestPages/boardSave.html
src/main/resources/templates/weatherCodiPages/boardDetail.html
src/main/resources/templates/weatherCodiPages/boardList.html
src/main/resources/templates/weatherCodiPages/boardUpdate.html

Hy admin board alarm 230704

---

src/main/java/com/example/weartheweather/controller/MemberController.java
src/main/java/com/example/weartheweather/entity/MemberEntity.java
src/main/java/com/example/weartheweather/service/MemberService.java
src/main/resources/templates/myInfoPages/myInfoUpdate.html

0704 업데이트 완료(but 라디오 타입 value값이 적용안됨 수정해야함)

0704 업데이트 완료(but 라디오 타입 value값이 적용안됨 수정해야함)

---

src/main/java/com/example/weartheweather/controller/AdminBoardController.java
src/main/java/com/example/weartheweather/controller/MemberBoardController.java
src/main/java/com/example/weartheweather/repository/MemberBoardLikesRepository.java
src/main/java/com/example/weartheweather/service/MemberBoardService.java
src/main/resources/templates/codiContestPages/boardDetail.html
src/main/resources/templates/codiContestPages/boardList.html
src/main/resources/templates/codiContestPages/boardSave.html
src/main/resources/templates/weatherCodiPages/boardDetail.html

하영_멤버게시글 디테일 좋아요 버튼 수정 임시저장

---

src/main/java/com/example/weartheweather/controller/AdminHomeController.java
src/main/java/com/example/weartheweather/controller/MemberController.java
src/main/resources/templates/adminIndex.html
src/main/resources/templates/component/adminnav.html
src/main/resources/templates/component/nav.html
src/main/resources/templates/memberPages/memberLogin.html
src/main/resources/templates/myInfoPages/myInfoUpdate.html

Dy memberadmin 0705

---

src/main/java/com/example/weartheweather/config/LoginCheckInterceptor.java
src/main/java/com/example/weartheweather/config/WebConfig.java
src/main/java/com/example/weartheweather/controller/AdminHomeController.java
src/main/java/com/example/weartheweather/controller/MemberController.java
src/main/java/com/example/weartheweather/controller/MyinfoController.java
src/main/java/com/example/weartheweather/service/MemberService.java
src/main/resources/application.yml
src/main/resources/templates/adminIndex.html
src/main/resources/templates/adminPages/boardDetail.html
src/main/resources/templates/adminPages/boardList.html
src/main/resources/templates/adminPages/boardSave.html
src/main/resources/templates/codiContestPages/boardList.html
src/main/resources/templates/component/adminnav.html
src/main/resources/templates/component/infonav.html
src/main/resources/templates/component/nav.html
src/main/resources/templates/memberPages/memberLogin.html
src/main/resources/templates/myInfoPages/myBoardList.html
src/main/resources/templates/myInfoPages/myInfoUpdate.html

0706 관리자페이지 수정 및 로그인 인터셉터 기능 완료

0706 관리자페이지 수정 및 로그인 인터셉터 기능 완료

---

src/main/java/com/example/weartheweather/controller/MemberBoardController.java
src/main/resources/templates/codiContestPages/boardDetail.html
src/main/resources/templates/codiContestPages/boardUpdate.html

+ memberLikes 기능완료 △ 쿠키를 활용하여 조회수 제어
△ 알림기능
△ 댓글기능
memberUpdate
△ 업데이트 폼 작성
△ 업데이트 기능

memberDetail

---

src/main/java/com/example/weartheweather/config/WebConfig.java
src/main/resources/templates/memberPages/memberSave.html

0706 MemberSave(Finish) 로그인(Finish), 로그인 인터셉터( 프로젝트 진행하면서 조금씩 수정해야할듯)

0706 MemberSave(Finish) 로그인(Finish), 로그인 인터셉터( 프로젝트 진행하면서 조금씩 수정해야할듯)

---

src/main/java/com/example/weartheweather/config/WebConfig.java
src/main/java/com/example/weartheweather/controller/MarketController.java
src/main/java/com/example/weartheweather/dto/MarketProductDTO.java
src/main/java/com/example/weartheweather/entity/MarketProductEntity.java
src/main/java/com/example/weartheweather/repository/MarketProductRepository.java
src/main/java/com/example/weartheweather/service/MarketProductService.java
src/main/resources/static/css/main.css
src/main/resources/templates/marketPages/marketDetail.html

Yh market 0707

---

src/main/java/com/example/weartheweather/controller/MemberBoardController.java
src/main/java/com/example/weartheweather/dto/MemberBoardDTO.java
src/main/java/com/example/weartheweather/entity/MemberBoardEntity.java
src/main/java/com/example/weartheweather/repository/MemberBoardRepository.java
src/main/java/com/example/weartheweather/service/MemberBoardService.java
src/main/resources/templates/codiContestPages/boardList.html
src/main/resources/templates/codiContestPages/boardPaging.html
src/main/resources/templates/component/nav.html

좋아요 기능 수정, 수정처리 수정, 조회수 쿠키설정 완료했습니다.

Hy member board 230708

---

src/main/java/com/example/weartheweather/config/LoginCheckInterceptor.java
src/main/java/com/example/weartheweather/controller/HomeController.java
src/main/java/com/example/weartheweather/controller/MemberController.java
src/main/resources/templates/component/config.html
src/main/resources/templates/index.html
src/main/resources/templates/memberPages/memberLogin.html

0709 로그인 인터셉터 후 보던 페이지로 넘어가는거 구현(아직 학원에서 확인해야함)

0709 로그인 인터셉터 후 보던 페이지로 넘어가는거 구현(아직 학원에서 확인해야함)

---

src/main/java/com/example/weartheweather/config/LoginCheckInterceptor.java
src/main/java/com/example/weartheweather/config/UserInterceptor.java
src/main/java/com/example/weartheweather/config/WebConfig.java
src/main/java/com/example/weartheweather/controller/AdminBoardController.java
src/main/java/com/example/weartheweather/controller/MemberController.java
src/main/java/com/example/weartheweather/controller/MyinfoController.java
src/main/java/com/example/weartheweather/service/AdminBoardService.java
src/main/resources/templates/adminPages/myLikeList.html
src/main/resources/templates/component/infonav.html
src/main/resources/templates/component/pagination.html
src/main/resources/templates/memberPages/memberLogin.html

0710 좋아요누른 리스트 ing

---

src/main/java/com/example/weartheweather/controller/AdminBoardController.java
src/main/java/com/example/weartheweather/controller/MemberBoardController.java
src/main/java/com/example/weartheweather/service/AdminBoardService.java
src/main/java/com/example/weartheweather/service/MemberBoardService.java
src/main/resources/templates/codiContestPages/boardList.html

Hy mb paging 230710

---

src/main/java/com/example/weartheweather/service/AdminBoardService.java

0710 충돌 수정

---

src/main/java/com/example/weartheweather/controller/CommentController.java
src/main/java/com/example/weartheweather/controller/MemberBoardController.java
src/main/java/com/example/weartheweather/dto/CommentDTO.java
src/main/java/com/example/weartheweather/dto/MemberBoardDTO.java
src/main/java/com/example/weartheweather/entity/CommentEntity.java
src/main/java/com/example/weartheweather/repository/CommentRepository.java
src/main/java/com/example/weartheweather/service/CommentService.java
src/main/resources/templates/codiContestPages/boardDetail.html

Hy mb comment 230710

---

src/main/java/com/example/weartheweather/controller/MyinfoController.java
src/main/java/com/example/weartheweather/repository/MarketLikesRepository.java
src/main/java/com/example/weartheweather/repository/MarketProductRepository.java
src/main/java/com/example/weartheweather/repository/MemberBoardRepository.java
src/main/java/com/example/weartheweather/service/AdminBoardService.java
src/main/java/com/example/weartheweather/service/MarketProductService.java
src/main/resources/templates/component/footer.html
src/main/resources/templates/component/infonav.html
src/main/resources/templates/myInfoPages/myDibsList.html

: 내가 썼던 글 리스트(myBoardList)
: 내가 웨더마켓에서 찜한 리스트(myDibsList)
완료
아직 페이징처리 및 css 남음

0710 마이페이지 : 내가 좋아요를 누른 글(myLikeList)

---

src/main/resources/templates/index.html
src/main/resources/templates/weatherCodiPages/boardList.html

0711 기상 정보 수정

---

src/main/java/com/example/weartheweather/controller/MemberBoardController.java
src/main/java/com/example/weartheweather/repository/MemberBoardLikesRepository.java
src/main/java/com/example/weartheweather/service/MemberBoardService.java
src/main/resources/templates/codiContestPages/boardDetail.html

Hy alarm 230712

---

src/main/java/com/example/weartheweather/controller/MarketController.java
src/main/java/com/example/weartheweather/controller/MarketPaymentController.java
src/main/java/com/example/weartheweather/dto/MarketPaymentDTO.java
src/main/java/com/example/weartheweather/dto/MarketProductDTO.java
src/main/java/com/example/weartheweather/entity/MarketPaymentEntity.java
src/main/java/com/example/weartheweather/entity/MarketProductEntity.java
src/main/java/com/example/weartheweather/repository/MarketPaymentRepository.java
src/main/java/com/example/weartheweather/repository/MemberBoardRepository.java
src/main/java/com/example/weartheweather/repository/MemberRepository.java
src/main/java/com/example/weartheweather/service/MarketPaymentService.java
src/main/resources/templates/marketPages/marketPayment.html
src/main/resources/templates/marketPages/marketPaymentSuccess.html

Yh market 0712

---

src/main/java/com/example/weartheweather/controller/MyinfoController.java
src/main/java/com/example/weartheweather/dto/MarketPaymentDTO.java
src/main/java/com/example/weartheweather/service/AdminBoardService.java
src/main/java/com/example/weartheweather/service/MarketPaymentService.java
src/main/resources/templates/adminPages/myLikeList.html
src/main/resources/templates/marketPages/marketPayment.html
src/main/resources/templates/memberPages/memberLogin.html
src/main/resources/templates/myInfoPages/myBoardList.html
src/main/resources/templates/myInfoPages/myDibsList.html

0713 마이페이지 페이징처리 완료

---

src/main/java/com/example/weartheweather/controller/MarketPaymentController.java
src/main/resources/static/css/main.css
src/main/resources/templates/marketPages/marketPaymentSuccess.html

△ 신고하기
△ 다중이미지파일 <-> 슬라이드
△ 채팅하기

△ 타임( ? 일전 )

---

src/main/java/com/example/weartheweather/controller/MyinfoController.java
src/main/java/com/example/weartheweather/dto/MarketPaymentDTO.java
src/main/java/com/example/weartheweather/entity/MarketPaymentEntity.java
src/main/java/com/example/weartheweather/repository/MarketPaymentRepository.java
src/main/java/com/example/weartheweather/service/AdminBoardService.java
src/main/resources/templates/component/infonav.html
src/main/resources/templates/myInfoPages/myTradeList.html

--> 구매확정 버튼을 누르면 컨트롤러에 넘기는 작업해야함

0713 거래내역 수정 및 마이페이지에 불러오기(불러오는것까지 확인)

---

src/main/java/com/example/weartheweather/controller/AlarmController.java
src/main/java/com/example/weartheweather/dto/AlarmDTO.java
src/main/java/com/example/weartheweather/entity/AlarmEntity.java
src/main/java/com/example/weartheweather/service/AlarmService.java
src/main/resources/templates/codiContestPages/boardDetail.html
src/main/resources/templates/component/nav.html

Hy alarm list 230714

---

src/main/java/com/example/weartheweather/controller/AdminBoardController.java
src/main/java/com/example/weartheweather/controller/AlarmController.java
src/main/java/com/example/weartheweather/entity/AlarmEntity.java
src/main/java/com/example/weartheweather/repository/AlarmRepository.java
src/main/java/com/example/weartheweather/service/AdminBoardService.java
src/main/java/com/example/weartheweather/service/AlarmService.java
src/main/resources/templates/component/nav.html
src/main/resources/templates/myInfoPages/myTradeList.html
src/main/resources/templates/weatherCodiPages/boardDetail.html

Hy is read 230714

---

src/main/java/com/example/weartheweather/controller/MemberBoardController.java
src/main/java/com/example/weartheweather/service/MemberBoardService.java
src/main/resources/templates/codiContestPages/boardList.html
src/main/resources/templates/codiContestPages/boardSave.html
src/main/resources/templates/marketPages/marketSave.html

현재 용현,하영 save할 때 파일첨부 없을 시 오류페이지가 뜨는것을 방지하는 코드 ing중

도영 - 코디콘테스트 페이징처리 및 제목,작성자에 따른 검색처리도 구현

---

src/main/java/com/example/weartheweather/controller/MarketController.java
src/main/resources/templates/component/nav.html
src/main/resources/templates/marketPages/marketDetail.html
src/test/java/com/example/weartheweather/WeatherTest.java

adminBoard 좋아요
market 좋아요 비동기 완료

좋아요 비동기 적용

---

src/main/java/com/example/weartheweather/controller/HomeController.java
src/main/java/com/example/weartheweather/controller/MarketController.java
src/main/java/com/example/weartheweather/service/MarketProductService.java
src/main/resources/templates/marketPages/marketList.html

0715 페이징처리 완료 (용현씨 웨더페이지에서 css적용이 안됨)

0715 페이징처리 완료 (용현씨 웨더페이지에서 css적용이 안됨)

---

src/main/java/com/example/weartheweather/controller/AdminBoardController.java
src/main/java/com/example/weartheweather/dto/AdminBoardDTO.java
src/main/resources/templates/adminPages/firstSearch.html
src/main/resources/templates/component/nav.html

0715 1차검색 페이지 ing

---

src/main/java/com/example/weartheweather/controller/MarketController.java
src/main/java/com/example/weartheweather/controller/MemberController.java
src/main/java/com/example/weartheweather/repository/MemberRepository.java
src/main/java/com/example/weartheweather/service/MemberService.java
src/main/resources/templates/codiContestPages/boardDetail.html

좋아요 addPoing 완료

---

src/main/java/com/example/weartheweather/controller/AdminBoardController.java
src/main/java/com/example/weartheweather/dto/PopularKeywordsDTO.java
src/main/java/com/example/weartheweather/entity/PopularKeywordsEntity.java
src/main/java/com/example/weartheweather/repository/PopularKeyWordsRepository.java
src/main/java/com/example/weartheweather/service/AdminBoardService.java
src/main/resources/templates/adminPages/firstSearch.html

0715 1차검색 페이지 ing (인기검색순으로 리스트에 저장되게 처리함)

0715 1차검색 페이지 ing (인기검색순으로 리스트에 저장되게 처리함)

---

src/main/java/com/example/weartheweather/controller/MemberBoardController.java
src/main/java/com/example/weartheweather/controller/MemberController.java
src/main/java/com/example/weartheweather/repository/MemberBoardRepository.java
src/main/java/com/example/weartheweather/repository/MemberRepository.java
src/main/java/com/example/weartheweather/service/MemberBoardService.java
src/main/java/com/example/weartheweather/service/MemberService.java
src/main/resources/templates/codiContestPages/boardDetail.html
src/main/resources/templates/codiContestPages/boardRankingList.html
src/main/resources/templates/codiContestPages/boardSave.html
src/main/resources/templates/component/nav.html

Hy comment point 230715

---

src/main/java/com/example/weartheweather/controller/AdminBoardController.java
src/main/resources/templates/adminPages/firstSearch.html
src/main/resources/templates/adminPages/secondSearch.html
src/main/resources/templates/memberPages/memberSave.html

도영 - 0717 아침 머지한 내용 수정후 다시 머지

---

src/main/java/com/example/weartheweather/controller/AdminBoardController.java
src/main/java/com/example/weartheweather/service/AdminBoardService.java
src/main/resources/templates/adminPages/secondSearch.html

도영 - 0717  1차 2차 검색 기본틀은 완료
- css 및 세부 조건 및 디테일을 잡아야함

도영 - 0717  1차 2차 검색 기본틀은 완료

---

src/main/resources/static/css/main.css
src/main/resources/templates/codiContestPages/boardSave.html
src/main/resources/templates/marketPages/marketSave.html
src/main/resources/templates/memberPages/memberSave.html

index 수정 ( 주간코디 작업중 )

---

src/main/java/com/example/weartheweather/config/WebSocketConfig.java
src/main/java/com/example/weartheweather/controller/ChatController.java
src/main/java/com/example/weartheweather/controller/ContactController.java
src/main/java/com/example/weartheweather/entity/Contact.java
src/main/java/com/example/weartheweather/handler/ChatHandler.java
src/main/java/com/example/weartheweather/repository/ContactRepository.java
src/main/java/com/example/weartheweather/service/ContactService.java
src/main/resources/templates/component/navMarket.html
src/main/resources/templates/marketPages/chat.html

0718 도영 1대1 채팅방 ing

---

src/main/java/com/example/weartheweather/controller/MarketController.java
src/main/java/com/example/weartheweather/controller/MemberBoardController.java
src/main/java/com/example/weartheweather/dto/CommentDTO.java
src/main/java/com/example/weartheweather/dto/MemberBoardDTO.java
src/main/java/com/example/weartheweather/repository/MemberBoardRepository.java
src/main/java/com/example/weartheweather/service/CommentService.java
src/main/java/com/example/weartheweather/service/MarketProductService.java
src/main/java/com/example/weartheweather/service/MemberBoardService.java
src/main/resources/templates/codiContestPages/boardDetail.html
src/main/resources/templates/marketPages/marketDetail.html
src/main/resources/templates/marketPages/marketUpdate.html

Hy member point 230718

---

src/main/java/com/example/weartheweather/controller/HomeController.java
src/main/java/com/example/weartheweather/dto/MemberBoardDTO.java
src/main/java/com/example/weartheweather/entity/MemberBoardEntity.java
src/main/resources/templates/codiContestPages/boardList.html
src/main/resources/templates/codiContestPages/boardRankingList.html
src/main/resources/templates/codiContestPages/boardSave.html
src/main/resources/templates/index.html

인덱스 랭킹리스트 90%

---

src/main/java/com/example/weartheweather/controller/MarketController.java
src/main/java/com/example/weartheweather/controller/MemberController.java
src/main/java/com/example/weartheweather/controller/MyinfoController.java
src/main/java/com/example/weartheweather/entity/MarketProductEntity.java
src/main/java/com/example/weartheweather/entity/MemberBoardLikesEntity.java
src/main/java/com/example/weartheweather/entity/MemberEntity.java
src/main/java/com/example/weartheweather/repository/MemberBoardLikesRepository.java
src/main/java/com/example/weartheweather/service/MarketProductService.java
src/main/java/com/example/weartheweather/service/MemberBoardLikesService.java
src/main/resources/templates/adminPages/myLikeList.html
src/main/resources/templates/component/mypageNav.html
src/main/resources/templates/marketPages/marketDetail.html
src/main/resources/templates/marketPages/marketUpdate.html
src/main/resources/templates/myInfoPages/myBoardList.html
src/main/resources/templates/myInfoPages/myDibsList.html
src/main/resources/templates/myInfoPages/myInfoUpdate.html

Hy market update 230719

---

src/main/resources/templates/adminPages/firstSearch.html
src/main/resources/templates/adminPages/myLikeList.html
src/main/resources/templates/myInfoPages/myBoardList.html
src/main/resources/templates/myInfoPages/myDibsList.html
src/main/resources/templates/myInfoPages/myTradeList.html

0719 도영 - 페이징처리 수정완료 및 검색 1차 수정 완료

0719 도영 - 페이징처리 수정완료 및 검색 1차 수정 완료

---

src/main/java/com/example/weartheweather/controller/HomeController.java
src/main/resources/templates/index.html

+ 코디예보 크롤링 적용중

---

src/main/java/com/example/weartheweather/controller/AdminBoardController.java
src/main/java/com/example/weartheweather/dto/PopularKeywordsDTO.java
src/main/java/com/example/weartheweather/service/AdminBoardService.java
src/main/java/com/example/weartheweather/service/MarketPaymentService.java
src/main/resources/templates/adminPages/boardSave.html
src/main/resources/templates/adminPages/firstSearch.html
src/main/resources/templates/adminPages/secondSearch.html
src/main/resources/templates/component/mypageNav.html

도영 - 검색2차 수정중 (키 , 성별에 따른 조건 검색은 완료)

도영 - 검색2차 수정중 (키 , 성별에 따른 조건 검색은 완료)

---

src/main/resources/templates/adminPages/firstSearch.html
src/main/resources/templates/adminPages/secondSearch.html

+ Search css 1차 완

---

src/main/java/com/example/weartheweather/controller/AdminHomeController.java
src/main/java/com/example/weartheweather/entity/AlarmEntity.java
src/main/java/com/example/weartheweather/entity/BaseEntity.java
src/main/java/com/example/weartheweather/service/MarketPaymentService.java
src/main/resources/templates/adminIndex.html
src/main/resources/templates/codiContestPages/boardDetail.html
src/main/resources/templates/codiContestPages/boardList.html
src/main/resources/templates/component/header.html
src/main/resources/templates/marketPages/marketPaymentSuccess.html

Hy admin point 230722

---

src/main/java/com/example/weartheweather/dto/CommentDTO.java
src/main/java/com/example/weartheweather/dto/MarketProductDTO.java
src/main/java/com/example/weartheweather/entity/BaseEntity.java
src/main/resources/templates/codiContestPages/boardDetail.html
src/main/resources/templates/marketPages/marketDetail.html

Hy comment 230722

---

src/main/java/com/example/weartheweather/dto/CommentDTO.java
src/main/java/com/example/weartheweather/dto/MarketProductDTO.java
src/main/java/com/example/weartheweather/entity/BaseEntity.java
src/main/resources/templates/codiContestPages/boardDetail.html
src/main/resources/templates/marketPages/marketDetail.html

memberBoardDetail

---

src/main/java/com/example/weartheweather/controller/AdminBoardController.java
src/main/java/com/example/weartheweather/dto/AdminBoardLikesDTO.java
src/main/resources/templates/codiContestPages/boardDetail.html
src/main/resources/templates/component/nav.html
src/main/resources/templates/index.html
src/main/resources/templates/weatherCodiPages/boardDetail.html

좋아요 비동기 출력 수정 완료
아이콘에 마이페이지 링크 연결

Hy board likes 230723

---

src/main/java/com/example/weartheweather/component/LoginCheckInterceptor.java
src/main/java/com/example/weartheweather/config/WebConfig.java
src/main/java/com/example/weartheweather/controller/AdminBoardController.java
src/main/java/com/example/weartheweather/controller/KakaoController.java
src/main/java/com/example/weartheweather/controller/MemberBoardController.java
src/main/java/com/example/weartheweather/controller/MemberController.java
src/main/resources/templates/component/nav.html
src/main/resources/templates/weatherCodiPages/boardDetail.html

좋아요 인터셉터 적용

---

src/main/java/com/example/weartheweather/config/LoginCheckInterceptor.java
src/main/java/com/example/weartheweather/controller/ChatController.java
src/main/java/com/example/weartheweather/controller/MemberBoardController.java
src/main/java/com/example/weartheweather/dto/AdminBoardDTO.java
src/main/java/com/example/weartheweather/dto/AdminDTO.java
src/main/java/com/example/weartheweather/service/AdminBoardService.java
src/main/java/com/example/weartheweather/service/WeatherService.java
src/main/resources/templates/adminPages/boardSave.html
src/main/resources/templates/adminPages/firstSearch.html
src/main/resources/templates/codiContestPages/boardSave.html
src/main/resources/templates/component/header.html
src/main/resources/templates/component/nav.html
src/main/resources/templates/index.html
src/main/resources/templates/marketPages/marketSave.html
src/main/resources/templates/memberPages/memberLogin.html

Hy test 230724

---

src/main/java/com/example/weartheweather/controller/MarketController.java
src/main/java/com/example/weartheweather/service/MarketProductService.java
src/main/resources/templates/marketPages/marketDetail.html

도영 - 마켓 디테일 연관상품 추가
